FROM eclipse-temurin:25-jre

ENV DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin LC_ALL=C
EXPOSE 25565
WORKDIR /data

RUN apt update && apt install jq nano curl -y 
RUN chown 1000:1000 /data
COPY start.sh          /srv/start.sh
COPY download-fabric.sh /srv/download-fabric.sh
COPY server.properties /srv/server.properties

RUN bash /srv/download-fabric.sh

USER 1000:1000

CMD [ "sh", "/srv/start.sh" ]
