FROM eclipse-temurin:25-jre

ENV DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin LC_ALL=C
EXPOSE 25565
WORKDIR /data

RUN apt update && apt install jq nano curl -y 
RUN useradd -ru 2000 minecraft && chown 2000:2000 /data
COPY start.sh          /srv/start.sh
COPY download-fabric.sh /srv/download-fabric.sh
COPY server.properties /srv/server.properties

RUN bash /srv/download-fabric.sh

USER 2000:2000

CMD [ "sh", "/srv/start.sh" ]
